#@Vishvanath Metkari

##What is NumPy?
NumPy is a Python library used for working with arrays.

It is the fundamental package for scientific computing with Python. It contains various features 

It also has functions for working in domain of linear algebra, fourier transform, and matrices.

NumPy stands for Numerical Python.




##Why is NumPy Faster Than Lists?
NumPy arrays are stored at one continuous place in memory unlike lists, so processes can access and manipulate them very efficiently.


##Which Language is NumPy written in?
NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.
2005

## Installation:


In [138]:
pip install numpy

first we need to import NumPy library:

In [139]:
import numpy as np


##1D vs **2D** Array
1D array (i.e., single dimensional array) stores a list of variables of the same data type. It is possible to access each variable using the index.

2D array (i.e, multi-dimensional array) stores data in a format consisting of rows and columns.

##Create a Vector
To create a vector, we simply create a one-dimensional array. Just like vectors, these arrays can be represented horizontally (i.e., rows) or vertically (i.e., columns).

In [3]:
#create 1 dimentional array (vector)
vector_row = np.array([1,2,3,4,5,6]) #create vector as a row
vector_row

array([1, 2, 3, 4, 5, 6])

In [4]:
vector_col = np.array([[1],[2],[3]])
vector_col

array([[1],
       [2],
       [3]])

In [141]:
vector_col.shape

(3, 1)

#Create a Matrix
the matrix contain three row and two columns

In [5]:
matrix = np.array([(1,2,3),(4,5,6)]) # Two dimensional array
matrix

array([[1, 2, 3],
       [4, 5, 6]])

##Creating a Sparse Matrix
A sparse matrix is a matrix in which most of the elements are zero. Sparse matrices only store nonzero elements and assume all other values will be zero

In [6]:
from scipy import sparse

matrix_large = np.array([[0, 0, 0, 0, 0, 0, 0, 6, 0, 0],
                         [0, 1, 0, 2, 0, 0, 0, 0, 0, 0],
                         [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])
matrix_large

array([[0, 0, 0, 0, 0, 0, 0, 6, 0, 0],
       [0, 1, 0, 2, 0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [7]:
# Create compressed sparse row (CSR) matrix
matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large_sparse)

  (0, 7)	6
  (1, 1)	1
  (1, 3)	2
  (2, 0)	3


##Create Special Ndarray

np.zeros() function returns a new array of given shape and type, filled with zero

In [8]:
#create 1d array of zeros , length 3
np.zeros(3)

array([0., 0., 0.])

In [9]:
# 2x3 array of zeros
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

np.ones() function returns a new array of given shape and type, filled with one

In [10]:
#create 3x4 array of onces
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

np.eye() function returns a matrix having 1’s on the diagonal and 0’s elsewhere

In [11]:
# Create 5x5 array of 0 with 1 on diagonal (Identity matrix)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

np.linspace() function returns an evenly spaced sequence in a specified interval

In [12]:
# Create an array of 5 evenly divided values from 0 to 10
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

np.arange(start, stop, step) function returns the ndarray object containing evenly spaced values within the given range.

The parameters determine the range of values:

start :defines the first value in the array.

stop :defines the end of the array and isn’t included in the array.

step: is the number that defines the spacing (difference) between every two consecutive values in the array and defaults to 1

In [13]:
# array values from 0 to less than with step 3
np.arange(0,10,3)

array([0, 3, 6, 9])

np.full(shape, fill_value) function returns a new array of a specified shape, fills with fill_value.

In [14]:
#2x3 array with all values 5
np.full( (2,3),5)

array([[5, 5, 5],
       [5, 5, 5]])

np.random.rand() function returns an array of specified shape and fills it with random values

In [21]:
# 2x3 array of random floats between 0 - 1
np.random.rand(2,3)

array([[0.43456889, 0.50661655, 0.59645386],
       [0.25829419, 0.46621009, 0.96669408]])

In [22]:
# 2x3 array of random floats between 0 - 100
np.random.rand(2,3)*100

array([[65.8837749 , 43.58533289, 88.60136092],
       [75.20295885, 13.30074575, 24.411814  ]])

In [23]:
# 2x3 array with random ints between 0-4
np.random.randint(0,4,size=(2,3))

array([[2, 3, 3],
       [1, 1, 0]])

## 2. Array shape manipulations

##Shape 
it will check the shape and size of the an array

Numpy array have an attribute called shape that returs a tuple 

In [30]:
arr = np.array([(1,2,3,4),(4,5,6,4),(7,8,9,4)])
print(arr)
arr.shape #return dimension of arr (row, column)

[[1 2 3 4]
 [4 5 6 4]
 [7 8 9 4]]


(3, 4)

reshape() allows us to restructure an array so that we maintain the same data but it is organized as a different number of rows and columns

The shape of the original and new matrix contains the same number of elements (i.e, same size)

In [34]:
arr1= np.arange(1,11)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [35]:
print(arr1.shape)

(10,)


We can usereshape() method to reshape our array to a 2 by 5 dimensional array.

In [36]:
arr1_2d = arr1.reshape((2,5))
arr1_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

If we want NumPy to automatically determine what size/length a particular dimension should be, specify the dimension as -1 which effectively means “as many as needed.” For example, reshape(2, -1) means two rows and as many columns as needed.

In [40]:
arr1.reshape(2,-1)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [39]:
arr1.reshape(5,-1)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [47]:
arr1.reshape(-1,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [37]:
arr1.reshape(-1,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

##Transpose
Transposing is a common operation in linear algebra where the column and row indices of each element are swapped

In [48]:
arr1_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [49]:
arr1_2d.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

##Flatten a Matrix
flatten() is a simple method to transform a matrix into a one-dimensional array.

In [50]:
arr1_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [51]:
arr1_2d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

##Resize a Matrix
resize(arr, new_shape) function returns a new array with the specified shape.
If the new array is larger than the original array, then the new array is filled with repeated copies of arr.

In [53]:
arr1_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [52]:
# Resize arr1_2d to 3 rows and 4 columns
resize_arr = np.resize(arr1_2d,(3,4))
resize_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10,  1,  2]])

##Convert Array to List and vice versa

In [57]:
my_list = [1,2,3,4]
print(my_list/4)

TypeError: ignored

In [58]:
my_array = np.array(my_list)
print(my_array/4)

[0.25 0.5  0.75 1.  ]


Arrays need to be declared whereas lists do not need declaration because they are a part of Python’s syntax. This is the reason lists are more often used than arrays. But in case of performing some arithmetic function to our list, we should go with arrays instead.

In case we want to store a large amount of data, we should consider arrays because they can store data very compactly and efficiently.

In [61]:
arr = np.array([(1,2,3),(4,5,6)])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [63]:
arr_to_list = arr.tolist()  #convert array to python list
arr_to_list

[[1, 2, 3], [4, 5, 6]]

In [64]:
np.array(arr_to_list)  #convert list to array


array([[1, 2, 3],
       [4, 5, 6]])

Other useful functions to describe the array:

In [67]:
print(arr.size) # Return number of elements in arr
print(len(arr) )#Length of arrayarr.ndim # Number of array dimension
print(arr.dtype )# Return type of elements in arr
print(arr.dtype.name) # Name of data type
print(arr.astype(int)) # Convert an array to a different type
print(np.info(np.eye) )# View documentation for np.eye



6
2
int64
int64
[[1 2 3]
 [4 5 6]]
None


##3. Numerical Operations on Array

Trace (linear algebra)
The trace is the sum of all the diagonal elements of a square matrix.

In [68]:
arr = np.array([(2,0,0),(0,2,0),(0,0,2)])
arr

array([[2, 0, 0],
       [0, 2, 0],
       [0, 0, 2]])

In [70]:
arr.shape

(3, 3)

In [72]:
np.trace(arr)

6

##Determinant
Determinants a matrix is a special number that can be calculated from a square matrix. It can sometimes be useful to calculate the determinant of a matrix. NumPy makes this easy with det().

A Matrix is an array of numbers:

3    8

4    6

A Matrix
(This one has 2 Rows and 2 Columns)

The determinant of that matrix is (calculations are explained later):

3×6 − 8×4 = 18 − 32 = −14

symbol : |A| means the determinant of the matrix A

In [75]:
matrix = np.array([(1,2,3),(4,5,6),(7,8,9)])
#return deteminant of matrix
np.linalg.det(matrix)  #linalg means  linear algebra toolset

0.0

##Find Eigenvalues and Eigenvectors

In NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues, and eigenvectors of any square matrix

In [78]:
matrix = np.array([(0,1,2),(3,4,5),(6,7,8)])

#calculate eigenvalue and eigenvectors
eigenvalues , eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print()
print(eigenvectors)

[ 1.33484692e+01 -1.34846923e+00 -1.15433316e-15]

[[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


##Scalar Operations
When we add, subtract, multiply or divide a matrix by a number, this is called the scalar operation. During scalar operations, the scalar value is applied to each element in the array, therefore, the function returns a new matrix with the same number of rows and columns.

In [80]:
new_arr = np.arange(1,10)
new_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [81]:
#add 1 to each array element
np.add(new_arr,1)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

Similarly, we can subtract, multiply, or divide a matrix by a number using functions below:

In [84]:
print(np.subtract(new_arr,2)) # Subtract 2 from each array element
print(np.multiply(new_arr,3)) # Multiply each array element by 3
print(np.divide(new_arr,4) )# Divide each array element by 4 (returns np.nan for division by zero)
print(np.power(new_arr,5) )# Raise each array element to the 5th power

[-1  0  1  2  3  4  5  6  7]
[ 3  6  9 12 15 18 21 24 27]
[0.25 0.5  0.75 1.   1.25 1.5  1.75 2.   2.25]
[    1    32   243  1024  3125  7776 16807 32768 59049]


##Matrics Operations
A matrix can only be added to (or subtracted from) another matrix if the two matrices have the same dimensions, that is, they must have the same number of rows and columns.
When multiplying matrices, we take rows of the first matrix and multiply them by the corresponding columns of the second matrix.

Note: Remember “rows first, columns second.”

In [85]:
# np.add(arr1,arr2) # Elementwise add arr2 to arr1
# np.subtract(arr1,arr2) # Elementwise subtract arr2 from arr1
# np.multiply(arr1,arr2) # Elementwise multiply arr1 by arr2
# np.divide(arr1,arr2) # Elementwise divide arr1 by arr2
# np.power(arr1,arr2) # Elementwise raise arr1 raised to the power of arr2
# np.array_equal(arr1,arr2) # Returns True if the arrays have the same elements and shape

###Other math operations:

In [87]:
print(np.sqrt(new_arr)) # Square root of each element in the array
print(np.sin(new_arr) )# Sine of each element in the array
print(np.log(new_arr) )# Natural log of each element in the array
print(np.abs(new_arr) )# Absolute value of each element in the array
print(np.ceil(new_arr)) # Rounds up to the nearest int
print(np.floor(new_arr)) # Rounds down to the nearest int
print(np.round(new_arr)) # Rounds to the nearest int

[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.        ]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155
  0.6569866   0.98935825  0.41211849]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
[1 2 3 4 5 6 7 8 9]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1. 2. 3. 4. 5. 6. 7. 8. 9.]
[1 2 3 4 5 6 7 8 9]


## 4. Array Manipulation Routines

###Adding/removing Elements
append() function is used to append values to the end of a given array.

In [90]:
np.append([0,3,2],[[3,5,7],[5,3,9]])


array([0, 3, 2, 3, 5, 7, 5, 3, 9])

In [94]:
np.append([[0,1,2],[3,4,5]],[[7,8,9]],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [7, 8, 9]])

The axis along which values are appended. If the axis is not given, both array and values are flattened before use.

insert(): is used to insert the element before the given index of the array.

In [97]:
arr = np.arange(1,6)
print(arr)
np.insert(arr,2,10) #insert 10 into arr before index 2 

[1 2 3 4 5]


array([ 1,  2, 10,  3,  4,  5])

delete() we can delete any row and column from the ndarray

In [99]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [100]:
np.delete(arr,2,axis=0)   #Delete row on index 2 of arr

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [101]:
np.delete(arr,3,axis=1)  #Delete column in index 3 of arr

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

sort() function can be used to sort the list in both ascending and descending order.

In [102]:
oned_arr = np.array([3,8,5,6,1])
np.sort(oned_arr)

array([1, 3, 5, 6, 8])

In [106]:
# sort each column of arr
arr = np.array([[5,4,6,8],
                [8,9,4,3],
                [0,7,5,2]])
np.sort(arr,axis=0)

array([[0, 4, 4, 2],
       [5, 7, 5, 3],
       [8, 9, 6, 8]])

In [107]:
# sort each row of X
np.sort(arr, axis=1)

array([[4, 5, 6, 8],
       [3, 4, 8, 9],
       [0, 2, 5, 7]])

Join NumPy Arrays
Joining means putting contents of two or more arrays in a single array.

In [109]:
# Adds arr2 as rows to the end of arr1
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2), axis=0)
arr

array([1, 2, 3, 4, 5, 6])

In [111]:
# Adds arr2 as columns to end of arr1
arr1 = np.array([[1, 2, 3],[4, 5, 6]])
arr2 = np.array([[7, 8, 9],[10, 11, 12]])
arr = np.concatenate((arr1,arr2),axis=1)
arr

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

## Split NumPy Arrays

In [112]:
# Splits arr into 4 sub_arrays
arr = np.array([1,2,3,4,5,6])
new_arr = np.array_split(arr ,4)
new_arr

[array([1, 2]), array([3, 4]), array([5]), array([6])]

In [114]:
#spilt arr horizontally on the 2nd index
new_arr = np.hsplit(arr,2)
new_arr

[array([1, 2, 3]), array([4, 5, 6])]

##Select element(s)
NumPy offers a wide variety of methods for indexing and slicing elements or groups of elements in arrays.

Suppose we have two arrays, one contains user_name, and the other stores the number of articles that the person has read.

In [115]:
user_name = np.array(['Katie','Bob','Scott','Liz','Sam'])
articles = np.array([100, 38, 91, 7, 25])
user_name[4] # Return the element at index 4

'Sam'

In [118]:
articles[3] = 17 # Assign array element on index 3 the value 17
articles

array([100,  38,  91,  17,  25])

In [120]:
user_name[0:3] # Return the elements at indices 0,1,2

array(['Katie', 'Bob', 'Scott'], dtype='<U5')

In [121]:
user_name[:2] # Return the elements at indices 0,1

array(['Katie', 'Bob'], dtype='<U5')

In [122]:
articles<50 # Return an array with boolean values

array([False,  True, False,  True,  True])

In [124]:
articles[articles < 50] # Return the element values

array([38, 17, 25])

In [125]:
# Return the user_name that read more than 50 articles but less than 100 articles
user_name[(articles < 100 ) & (articles >50)]

array(['Scott'], dtype='<U5')

##5. Statistical Operations

Find the Maximum and Minimum Values

In [126]:
articles = np.array([[10, 23, 17],
                   [41, 54, 65],
                   [71, 18, 89]])
# Return maximum element
np.max(articles)

89

In [127]:
np.max(articles, axis=0) # Find maximum element in each column

array([71, 54, 89])

In [129]:
np.max(articles, axis=1) # Find maximum element in each row

array([23, 65, 89])

##Calculate the Average, Variance, and Standard Deviation
Just like with max() and min(), we can easily get descriptive statistics about the whole matrix or do calculations along a single axix

In [137]:
print(np.mean(articles,axis=0))# Return mean along specific axis
print(articles.sum()) # Return sum of arr
print(np.var(articles)) # Return the variance of array
print(np.std(articles,axis=0)) # Return the standard deviation of specific axis
print(np.corrcoef(articles)) # Return correlation coefficient of array

[40.66666667 31.66666667 57.        ]
388
699.8765432098766
[24.90426113 15.92342788 29.93325909]
[[ 1.          0.57782122 -0.68637604]
 [ 0.57782122  1.          0.19694956]
 [-0.68637604  0.19694956  1.        ]]
